services:
  - type: web
    name: chat-group-app
    env: python
    plan: free  # Adjust this based on your needs
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -p 8000 chatapp.asgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key_here
      - key: DJANGO_SETTINGS_MODULE
        value: chatapp.settings
